In [1]:
from qoptcraft import Fock
from qoptcraft.optimization import HeraldedStatePrep, GubarevCost
from piquasso_optimization import PiquassoOptimizer

import sys, os
sys.path.insert(0, os.path.abspath('../..'))
from results_table import benchmarks_table

# Bell

In [2]:
in_state = Fock(1,1,1,1,0,0)
target_state = Fock(1,0,1,0) + Fock(0,1,0,1)
herald = Fock(1,1)
problem = HeraldedStatePrep(in_state, target_state, herald)
cost_fun = GubarevCost(problem)
opt = PiquassoOptimizer(in_state, target_state, herald)

In [3]:
N_RUNS = 1000
results = [opt.minimize() for _ in range(N_RUNS)]
all_results = {"Piquasso": results}

In [4]:
PROB_THRESH = 0.073
benchmarks_table(all_results, problem, PROB_THRESH)

           Runs Converged (%) Mean time (s) Mean iters
Optimizer
Piquasso   1000         63.1%          0.31        397

# NOON

In [5]:
in_state = Fock(2,2,2,0)
target_state = Fock(5,0) + Fock(0,5)
herald = Fock(1,0)
problem = HeraldedStatePrep(in_state, target_state, herald)
cost_fun = GubarevCost(problem)
opt = PiquassoOptimizer(in_state, target_state, herald)

In [6]:
N_RUNS = 10000
results = [opt.minimize() for _ in range(N_RUNS)]
all_results = {"Piquasso": results}

In [7]:
PROB_THRESH = 0.055
benchmarks_table(all_results, problem, PROB_THRESH)

            Runs Converged (%) Mean time (s) Mean iters
Optimizer
Piquasso   10000         41.6%          0.12        206

# GHZ

In [8]:
in_state = Fock(1,1,1,1,1,1) * Fock(0,0,0,0)
target_state = Fock(0,1,0,1,0,1) + Fock(1,0,1,0,1,0)
herald = Fock(1,1,1,0)
problem = HeraldedStatePrep(in_state, target_state, herald)
cost_fun = GubarevCost(problem)
opt = PiquassoOptimizer(in_state, target_state, herald)

In [9]:
N_RUNS = 100
results = [opt.minimize() for _ in range(N_RUNS)]
all_results = {"Piquasso": results}

In [ ]:
PROB_THRESH = 0.0091
benchmarks_table(all_results, problem, PROB_THRESH)